AWSTemplateFormatVersion: 2010-09-09
Transform: AWS::Serverless-2016-10-31 
Parameters:
  VpcID:
    Type: String
    Description: The VPC for Lambda 
  OwnerName:
      Type: String
      Description: Owner Name for project      
  Environment:
      Type: String
      Description: Enviroment Name for project  

Resources:
  SecurityGroup:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupDescription: Allow http to client host
      GroupName : !Sub bitly-${Environment}-SG
      VpcId:
         Ref: VpcID
      SecurityGroupIngress:
      - IpProtocol: tcp
        FromPort: 80
        ToPort: 80
        CidrIp: 172.27.113.10/32
      - IpProtocol: tcp
        FromPort: 443
        ToPort: 443
        CidrIp: 172.27.113.10/32
      - IpProtocol: tcp
        FromPort: 80
        ToPort: 80
        CidrIp: 172.27.117.10/32
      - IpProtocol: tcp
        FromPort: 443
        ToPort: 443
        CidrIp: 172.27.117.10/32

      # SecurityGroupEgress:
      # - IpProtocol: -1
      #   # FromPort: 80
      #   # ToPort: 80
      #   CidrIp: 0.0.0.0/0 
      # # - IpProtocol: -1
      # #   FromPort: 80
      # #   ToPort: 443
      # #   CidrIp: 0.0.0.0/0

Outputs:
  SecurityGroup:
     Description: Security group name
     Value: !Ref SecurityGroup
     Export:
       Name: !Sub ${AWS::StackName}-SecurityGroup      