AWSTemplateFormatVersion: 2010-09-09
Transform: AWS::Serverless-2016-10-31
Parameters:
  VpcID:
    Type: String
    Description: The VPC for Lambda
  OwnerName:
    Type: String
    Description: Owner Name for project
  Environment:
    Type: String
    Description: Enviroment Name for project
Resources:
  SecurityGroup:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupDescription: Allow http to client host
      GroupName:
        Fn::Sub: ${Environment}-bitly-SG
      VpcId:
        Ref: VpcID
      SecurityGroupIngress:
      - IpProtocol: tcp
        FromPort: 80
        ToPort: 80
        CidrIp: 0.0.0.0/0
      SecurityGroupEgress:
      - IpProtocol: tcp
        FromPort: 80
        ToPort: 80
        CidrIp: 0.0.0.0/0
      - IpProtocol: tcp
        FromPort: 80
        ToPort: 443
        CidrIp: 0.0.0.0/0
Outputs:
  SecurityGroup:
    Description: Security group name
    Value:
      Ref: SecurityGroup
    Export:
      Name:
        Fn::Sub: ${AWS::StackName}-SecurityGroup