AWSTemplateFormatVersion: 2010-09-09
Transform: AWS::Serverless-2016-10-31 

Parameters:
  OwnerName:
      Type: String
      Description: Owner Name for project      
  Environment:
      Type: String
      Description: Enviroment Name for project   
Resources:
  S3DocsBucket:
    Type: AWS::S3::Bucket
    DeletionPolicy: Retain
    Properties:
      BucketName: bitly-prod-output-files
      PublicAccessBlockConfiguration: 
        BlockPublicAcls: TRUE
        BlockPublicPolicy: TRUE
        IgnorePublicAcls: TRUE
        RestrictPublicBuckets: TRUE  