---
TemplateBody:
  AWSTemplateFormatVersion: '2010-09-09'
  Resources:
    S3DocsBucket:
      DeletionPolicy: Retain
      Type: AWS::S3::Bucket
      Properties:
        PublicAccessBlockConfiguration:
          IgnorePublicAcls: true
          BlockPublicPolicy: true
          BlockPublicAcls: true
          RestrictPublicBuckets: true
        BucketName: bitly-prod-docs
  Parameters:
    Environment:
      Type: String
      Description: Enviroment Name for project
    OwnerName:
      Type: String
      Description: Owner Name for project
