AWSTemplateFormatVersion: 2010-09-09

Parameters:
  ExportStackUserTableName:
    Description: The name userdb table name
    Type: String
  ExportStackCampaignTableName:
    Description: The name CampaignTable name
    Type: String
  ExportStackAuthTableName:
    Description: The name AuthTable name
    Type: String
  ExportStackLogsTableName:
    Description: The name LogsTable name
    Type: String
  bucketname: 
    Description: output file bucket
    Type: String  
  Owner: 
    Description: owner name 
    Type: String  
Resources:
  ECSRole:
   Type: "AWS::IAM::Role"
   Properties:
     RoleName: "bitly-ecs-taskdefination-Role"  
     Path: "/"
     Tags:
       - 
         Key : "Project"
         Value: "Bitly"
         Key: "Owner"
         Value: !Ref Owner
         Key: "Environment"
         Value: !Ref Environment
         Key: "Application"
         Value: "Bitly"     
     ManagedPolicyArns:
        - "arn:aws:iam::aws:policy/service-role/AmazonECSTaskExecutionRolePolicy"
        - "arn:aws:iam::aws:policy/service-role/AmazonEC2ContainerServiceforEC2Role" 
        - "arn:aws:iam::aws:policy/service-role/AmazonEC2RoleforSSM"
     AssumeRolePolicyDocument:
       Version: "2012-10-17"
       Statement:
         - Effect: "Allow"
           Action:
             - "sts:AssumeRole"
           Principal:
             Service:
               - "ecs-tasks.amazonaws.com"
     Policies:
     - PolicyName: kms-policy
       PolicyDocument:
         Version: '2012-10-17'
         Statement:
         - Effect: Allow
           Action:
           - kms:Encrypt
           - kms:Decrypt
           - kms:ReEncrypt*
           - kms:GenerateDataKey*
           - kms:DescribeKey
           - kms:CreateGrant 
           Resource: '*'
           Action: kms:*
           Resource:
           - arn:aws:kms:ap-south-1:542343947608:key/738e882f-2db5-4013-ad1d-161293386af9
           - arn:aws:kms:ap-south-1:542343947608:key/2c26baba-7aac-45e6-88dc-c5b5c8b96e3d
           - arn:aws:kms:ap-south-1:542343947608:key/a67166cf-6da7-4083-abd3-2d06296f5c46
           - arn:aws:kms:ap-south-1:542343947608:key/b287fb93-6dd3-478f-9de9-9e9c8c0740af

     - PolicyName: S3-CrudAccess
       PolicyDocument:
         Version: '2012-10-17'
         Statement:
         - Effect: Allow
           Action:
           - s3:GetObject
           - s3:ListBucket
           - s3:GetBucketLocation
           - s3:GetObjectVersion
           - s3:PutObject
           - s3:PutObjectAcl
           - s3:GetLifecycleConfiguration
           - s3:PutLifecycleConfiguration
           - s3:DeleteObject
           Resource:
           - Fn::Sub: arn:${AWS::Partition}:s3:::${bucketname}
           - Fn::Sub: arn:${AWS::Partition}:s3:::${bucketname}/*           

     - PolicyName: DynamoDb-Access
       PolicyDocument:
         Version: '2012-10-17'
         Statement:
         - Effect: Allow
           Action:
           - dynamodb:GetItem
           - dynamodb:DeleteItem
           - dynamodb:PutItem
           - dynamodb:Scan
           - dynamodb:Query
           - dynamodb:UpdateItem
           - dynamodb:BatchWriteItem
           - dynamodb:BatchGetItem
           - dynamodb:DescribeTable
           - dynamodb:GetRecords
           - dynamodb:Scan
           - dynamodb:UpdateTable
           Resource:
           - Fn::ImportValue:
               Fn::Sub: ${ExportStackUserTableName}-UserDynamoDbTable
           - Fn::ImportValue:
               Fn::Sub: ${ExportStackCampaignTableName}-CampaignDynamodbTable
           - Fn::ImportValue:
               Fn::Sub: ${ExportStackAuthTableName}-AuthDynamoDBtable
           - Fn::ImportValue:
               Fn::Sub: ${ExportStackLogsTableName}-LogsDynamoDbTable 
         - Effect: Allow
           Action:
           - dynamodb:Query
           - dynamodb:Scan
           Resource: 
           - arn:aws:dynamodb:ap-south-1:251899213637:table/Prod-bitly-user-table/index/campaign_name-index               


# Outputs:
#   ECSRoleoutput:
#      Description: ecs role
#      Value: !GetAtt ECSRoleoutput.Arn
#      Export: 
#        Name: !Sub ${AWS::StackName}-ECSRoleoutput