AWSTemplateFormatVersion: 2010-09-09
Transform: AWS::Serverless-2016-10-31
Parameters:
  OwnerName:
    Type: String
    Description: Owner Name for project
  Environment:
    Type: String
    Description: Enviroment Name for project
Resources:
  userDynamoDBtable:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName:
        Fn::Sub: ${Environment}-bitly-user-table
      AttributeDefinitions:
      - AttributeName: user_id
        AttributeType: S
      - AttributeName: campaign_name
        AttributeType: S
      KeySchema:
      - AttributeName: user_id
        KeyType: HASH
      GlobalSecondaryIndexes:
      - IndexName: campaign_name-index
        Projection:
          ProjectionType: ALL
        KeySchema:
        - KeyType: HASH
          AttributeName: campaign_name
        ProvisionedThroughput:
          WriteCapacityUnits: 5
          ReadCapacityUnits: 5
      SSESpecification:
        SSEEnabled: true
        SSEType: KMS
      ProvisionedThroughput:
        WriteCapacityUnits: 5
        ReadCapacityUnits: 5
      Tags:
      - Key: Application
        Value: HDFC-BITLY
Outputs:
  Tablename:
    Description: table Name
    Value:
      Ref: userDynamoDBtable
    Export:
      Name:
        Fn::Sub: ${AWS::StackName}-tablename
  UserDynamoDbTable:
    Description: Role for lambda
    Value:
      Fn::GetAtt:
      - userDynamoDBtable
      - Arn
    Export:
      Name:
        Fn::Sub: ${AWS::StackName}-UserDynamoDbTable