---
AWSTemplateFormatVersion: 2010-09-09
Resources:
  CloudwatcheventRole:
    Type: AWS::IAM::Role
    Properties:
      RoleName:
        Fn::Sub: bitly-Production-cloudwatch-event-role
      Path: /
      Tags:
      - Key: Application
        Value: Bitly
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
        - Effect: Allow
          Action:
          - sts:AssumeRole
          Principal:
            Service:
            - events.amazonaws.com
      Policies:
      - PolicyName: task-role
        PolicyDocument:
          Version: '2012-10-17'                    
          Statement:
          - Effect: Allow
            Action:
            - ecs:RunTask
            - ecs:StopTask
            Resource: "*"
            Condition:
              ArnLike:
                ecs:cluster:
                - arn:aws:ecs:ap-south-1:251899213637:cluster/bitly-prod-cluster            
          - Effect: Allow
            Action: iam:PassRole
            Resource: "*"
            Condition:
              StringLike:
                iam:PassedToService: ecs-tasks.amazonaws.com

Outputs:
  CloudwatcheventRole:
#    Description: Lambda for generate otp
    Value:
      Fn::GetAtt:
      - CloudwatcheventRole
      - Arn
    Export:
      Name:
        Fn::Sub: ${AWS::StackName}-CloudwatcheventRole      