AWSTemplateFormatVersion: 2010-09-09

Parameters:
  SubnetID1:
    Type: String
    Description: The Subnet for Lambda
  ExportStackNameSG:
    Type: String
    Description: Security group for ecs service  
  Environment:
    Description: Name of Env
    Type: String
  ClusterARN:
    Description: ARN of cluster
    Type: String
  TaskDefinitionArn: 
    Type: String
    Description: task defination arn
  EventRoleARN: 
    Type: String
    Description: role arn for event rule   


Resources:
  ScheduledRule:
    Type: AWS::Events::Rule
    Properties:
      Description: "ScheduledRule"
      Name:  !Sub bitly-${Environment}-download-report
#      RoleArn: !Ref RoleNameARN   
      ScheduleExpression: "cron(36 10 * * ? *)"
      State: ENABLED
      Targets: 
        - Arn: !Ref ClusterARN
          EcsParameters:
            Group: ECS TASK
            LaunchType: FARGATE
            NetworkConfiguration:
              AwsVpcConfiguration:
                AssignPublicIp: DISABLED
                SecurityGroups: 
                - Fn::ImportValue: !Sub '${ExportStackNameSG}-SecurityGroup'
                Subnets: 
                  - !Ref SubnetID1
            PlatformVersion: LATEST
            TaskCount: 1
            TaskDefinitionArn: !Ref TaskDefinitionArn
          Id: !Sub bitly-${Environment}-downloadreport
          RoleArn: !Ref EventRoleARN  
